import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import journal from '../src/db/migrations/meta/_journal.json';

const migrationsDir = resolve(import.meta.dir, '../src/db/migrations');
const outPath = resolve(import.meta.dir, '../src/db/migrations.bundle.ts');

const entries = [];

for (const entry of journal.entries) {
  const sql = await readFile(resolve(migrationsDir, `${entry.tag}.sql`), 'utf8');
  entries.push({
    tag: entry.tag,
    when: entry.when,
    sql,
  });
}

const contents = `/* eslint-disable */
// Generated by scripts/bundle-migrations.ts — do not edit manually.
export const bundledMigrations = ${JSON.stringify(entries, null, 2)} as const;
`;

await writeFile(outPath, contents);
console.log(`Bundled ${entries.length} migrations → src/db/migrations.bundle.ts`);
